# Lesson 4 Practice: Pandas Part 2

Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L04-Pandas_Part2-Lesson.ipynb](./L04-Pandas_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired.  

## Task 1a: Setup

- import pandas
- re-create the `df` data frame
- re-create the `iris_df` data frame

In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame(
    {'alpha': [0, 1, 2, 3, 4],
     'beta': ['a', 'b', 'c', 'd', 'e']})
iris_df = pd.read_csv('Data-Analytics-With-Python/Data-Analytics-With-Python/data/iris.csv')

## Task 2a: Inserting Columns

+ Create a copy of the `df` dataframe.
+ Add a new column named "delta" to the copy that consists of random numbers.

In [5]:
print("df data frame:\n", df)
delta = np.random.random(5)
print("\n\nadded delta column:")
df['delta'] = delta
df

df data frame:
    alpha beta     delta
0      0    a  0.296171
1      1    b  0.774631
2      2    c  0.398240
3      3    d  0.146822
4      4    e  0.781446


added delta column:


alpha beta     delta
0      0    a  0.836489
1      1    b  0.885598
2      2    c  0.305410
3      3    d  0.284152
4      4    e  0.871146

## Task 3a: Missing Data

+ Create two new copies of the `df` dataframe:
+ Add a new column to both that has missing values.
+ In one copy, replace missing values with a value of your choice.
+ In the other copy, drop rows with `NaN` values.
+ Print both arrays to confirm.

In [14]:
df['gamma'] = ''
df['kappa'] = np.nan
print("added missing values:\n", df)
df1 = df
print("\ncopy of df:\n", df1)
print("\nfill missing values:\n", df.fillna(0))
print("\ndrop nan rows:\n", df1.dropna())

added missing values:
    alpha beta     delta gamma  kappa
0      0    a  0.836489          NaN
1      1    b  0.885598          NaN
2      2    c  0.305410          NaN
3      3    d  0.284152          NaN
4      4    e  0.871146          NaN

copy of df:
    alpha beta     delta gamma  kappa
0      0    a  0.836489          NaN
1      1    b  0.885598          NaN
2      2    c  0.305410          NaN
3      3    d  0.284152          NaN
4      4    e  0.871146          NaN

fill missing values:
    alpha beta     delta gamma  kappa
0      0    a  0.836489          0.0
1      1    b  0.885598          0.0
2      2    c  0.305410          0.0
3      3    d  0.284152          0.0
4      4    e  0.871146          0.0

drop nan rows:
 Empty DataFrame
Columns: [alpha, beta, delta, gamma, kappa]
Index: []


## Task 4a: Operations
<span style="float:right; margin-left:10px; clear:both;">![Task](./media/task-icon.png)</span>

View the [Computational tools](https://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html) and [statistical methods](https://pandas.pydata.org/pandas-docs/stable/user_guide/computation.html#method-summary) documentation.
Using the list of operational functions choose five functions to use with the iris data frame.



In [24]:
iris_df.head()
print("mean by column:\n", iris_df.mean(0))
print("\nminimum by column:\n", iris_df.min(0))
print("\nmaximum by column:\n", iris_df.max(0))
print("\nstandard deviation by column:\n", iris_df.std(0))
print("\nvariance by column:\n", iris_df.var(0))

mean by column:
 sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64

minimum by column:
 sepal_length       4.3
sepal_width          2
petal_length         1
petal_width        0.1
species         setosa
dtype: object

maximum by column:
 sepal_length          7.9
sepal_width           4.4
petal_length          6.9
petal_width           2.5
species         virginica
dtype: object

standard deviation by column:
 sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
dtype: float64

variance by column:
 sepal_length    0.685694
sepal_width     0.188004
petal_length    3.113179
petal_width     0.582414
dtype: float64


## Task 4b:  Apply

Practice using `apply` on either the `df` or `iris_df` data frames using any two functions of your choice other than `print`, `type`, and `np.sum`.

In [38]:
df.apply(lambda x: x + 5)
df.apply(np.log)

TypeError: ('can only concatenate str (not "int") to str', 'occurred at index beta')

## Task 4c.  Occurances
Ientify the number of occurances for each species (virginica, versicolor, setosa) in the `iris_df` object.  *Hint*: the `value_counts` function only works on a `pd.Series` object, not on the full data frame..

In [43]:
s = pd.Series(data = iris_df, index = ('virginica','versicolor','setosa'))
s.value_counts()

ValueError: Length of passed values is 150, index implies 3

## Task 5a: String Methods

+ Create a list of five strings that represent dates in the form YYYY-MM-DD (e.g. 2020-02-20 for Feb 20th, 2020).
+ Add this list of dates as a new column in the `df` dataframe.
+ Now split the date into 3 new columns with one column representing the year, another the month and another they day.
+ Combine the values from columns `alpha` and `beta` into a new column where the values are spearated with a colon.


In [59]:
date = [['2019-01-28'],['2020-03-24'],['2018-08-17'],['2020-09-07'],['2019-10-23']]
print("dates:\n", date)
df['dates'] = date
s = df
print("\ncopied array:\n", s)
print("\nsplit dates column\n:", s['dates'].str.split(n=3))
df['lambda'] = df['alpha'] + '_' + df['beta']
print("\ncombined alpha and beta:\n", df)

dates:
 [['2019-01-28'], ['2020-03-24'], ['2018-08-17'], ['2020-09-07'], ['2019-10-23']]

copied array:
    alpha beta     delta gamma  kappa         dates
0      0    a  0.836489          NaN  [2019-01-28]
1      1    b  0.885598          NaN  [2020-03-24]
2      2    c  0.305410          NaN  [2018-08-17]
3      3    d  0.284152          NaN  [2020-09-07]
4      4    e  0.871146          NaN  [2019-10-23]

split dates column
: 0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: dates, dtype: float64


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

## Task 6a: Concatenation by Rows
+ Create the following dataframe
```Python
df1 = pd.DataFrame(
    {'alpha': [0, 1, 2, 3, 4],
     'beta': ['a', 'b', 'c', 'd', 'e']}, index = ['I1', 'I2' ,'I3', 'I4', 'I5'])
```
+ Create a new dataframe named `df2` with column names "delta" and "gamma" that contins 5 rows with some index names that overlap with the `df1` dataframe and some that do not.
+ Concatenate the two dataframes by rows and print the result.
+ You should see the two have combined one after the other, but there should also be missing values added. 
+ Explain why there are missing values.


In [65]:
df1 = pd.DataFrame(
  {'alpha': [0, 1, 2, 3, 4],
   'beta': ['a', 'b', 'c', 'd', 'e']}, index = ['I1', 'I2' ,'I3', 'I4', 'I5'])
df2 = pd.DataFrame(
 {'delta': [8, 7, 6, 5, 4],
  'gamma': ['a', 'c', 'b', 'd', 'e']}, index = ['I1', 'I2' ,'K1', 'K2', 'K3'])
pd.concat([df1, df2], axis=1, sort=True)

alpha beta  delta gamma
I1    0.0    a    8.0     a
I2    1.0    b    7.0     c
I3    2.0    c    NaN   NaN
I4    3.0    d    NaN   NaN
I5    4.0    e    NaN   NaN
K1    NaN  NaN    6.0     b
K2    NaN  NaN    5.0     d
K3    NaN  NaN    4.0     e

## Task 6b: Concatenation by Columns

Using the same dataframes, df1 and df2, from Task 6a practice:
+ Concatenate the two by columns
+ Add a "delta" column to `df1` and concatenate by columns such that there are 5 columns in the merged dataframe.
+ Respond in writing to this question (add a new 'raw' cell to contain your answer). What will happen if using you had performed an inner join while concatenating?  
+ Try the concatenation with the inner join to see if you are correct.

In [71]:
pd.concat([df1, df2], axis=1, sort=False)
df1['delta'] = [0, 1, 0, 1, 0]
pd.concat([df1, df2], axis=1, sort=False, join = 'inner')

alpha beta  delta  delta gamma
I1      0    a      0      8     a
I2      1    b      1      7     c

#### Task 6c: Concat and append data frames
<span style="float:right; margin-left:10px; clear:both;">![Task](./media/task-icon.png)</span>

+ Create a new 5x5 dataframe full of random numbers.
+ Create a new 5x10 dataframe full of 1's.
+ Append one to the other and print it.
+ Append a single Series of zeros to the end of the appended dataframe.


In [79]:
df_new = np.random.random((5, 5))
print("random dataframe:\n", df_new)
df_on = np.ones((5,10))
print("\nones dataframe:\n", df_on)
print("\nappended dataframe:\n", df_new.append(df_on, ignore_index=True))


random dataframe:
 [[0.92098531 0.69925047 0.51439486 0.48036276 0.86272829]
 [0.52757843 0.48142072 0.13611497 0.56602384 0.57852212]
 [0.5770015  0.57487986 0.32798781 0.67458646 0.48517241]
 [0.11621228 0.30500086 0.10269162 0.95012853 0.46191323]
 [0.69339342 0.85975923 0.4529245  0.25988052 0.47467496]]

ones dataframe:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


AttributeError: 'numpy.ndarray' object has no attribute 'append'

## Task 6d: Grouping

Demonstrate a `groupby`.

+ Create a new column with the label "region" in the iris data frame. This column will indicates geographic regions of the US where measurments were taken. Values should include:  'Southeast', 'Northeast', 'Midwest', 'Southwest', 'Northwest'. Use these randomly.
+ Use `groupby` to get a new data frame of means for each species in each region.
+ Add a `dev_stage` column by randomly selecting from the values "early" and "late".
+ Use `groupby` to get a new data frame of means for each species,in each region and each development stage.
+ Use the `count` function (just like you used the `mean` function) to identify how many rows in the table belong to each combination of species + region + developmental stage.

In [83]:
iris_df['region']= np.random.choice(['Southeast', 'Northeast', 'Midwest', 'Southwest', 'Northwest'], iris_df.shape[0])
groups = iris_df.groupby(['species', 'region'])
groups.mean()
iris_df['dev_stage'] = np.random.choice(['early', 'late'], iris_df.shape[0])
iris_df.mean()
new = iris_df.groupby(['species', 'region', 'dev_stage'])
new.count()

sepal_length  sepal_width  petal_length  \
species    region    dev_stage                                            
setosa     Midwest   early                 2            2             2   
                     late                  4            4             4   
           Northeast early                 5            5             5   
                     late                  4            4             4   
           Northwest early                 4            4             4   
                     late                  5            5             5   
           Southeast early                 8            8             8   
                     late                  9            9             9   
           Southwest early                 5            5             5   
                     late                  4            4             4   
versicolor Midwest   early                 7            7             7   
                     late                  8            8             8   
           Northeast early                 1            1             1   
                     late                  3            3             3   
           Northwest early                 4            4             4   
                     late                  3            3             3   
           Southeast early                 3            3             3   
                     late                  4            4             4   
           Southwest early                 8            8             8   
                     late                  9            9             9   
virginica  Midwest   early                 5            5             5   
                     late                  6            6             6   
           Northeast early                 6            6             6   
                     late                  2            2             2   
           Northwest early                 5            5             5   
                     late                  5            5             5   
           Southeast early                 3            3             3   
                     late                  6            6             6   
           Southwest early                 5            5             5   
                     late                  7            7             7   

                                petal_width  
species    region    dev_stage               
setosa     Midwest   early                2  
                     late                 4  
           Northeast early                5  
                     late                 4  
           Northwest early                4  
                     late                 5  
           Southeast early                8  
                     late                 9  
           Southwest early                5  
                     late                 4  
versicolor Midwest   early                7  
                     late                 8  
           Northeast early                1  
                     late                 3  
           Northwest early                4  
                     late                 3  
           Southeast early                3  
                     late                 4  
           Southwest early                8  
                     late                 9  
virginica  Midwest   early                5  
                     late                 6  
           Northeast early                6  
                     late                 2  
           Northwest early                5  
                     late                 5  
           Southeast early                3  
                     late                 6  
           Southwest early                5  
                     late                 7