# Lesson 2 Practice: NumPy Part 2
Use this notebook to follow along with the lesson in the corresponding lesson notebook: [L02-Numpy_Part2-Lesson.ipynb](./L02-Numpy_Part2-Lesson.ipynb).  


## Instructions
Follow along with the teaching material in the lesson. Throughout the tutorial sections labeled as "Tasks" are interspersed and indicated with the icon: ![Task](http://icons.iconarchive.com/icons/sbstnblnd/plateau/16/Apps-gnome-info-icon.png). You should follow the instructions provided in these sections by performing them in the practice notebook.  When the tutorial is completed you can turn in the final practice notebook. For each task, use the cell below it to write and test your code.  You may add additional cells for any task as needed or desired. 

## Task 1a: Setup

In the practice notebook, import the following packages:
+ `numpy` as `np`

In [1]:
import numpy as np

## Task 2a: Indexing by Subsetting and Slicing

In the practice notebook perform the following:

1. Create (or re-use) 3 arrays, each containing three dimensions.
2. Slice each of these arrays so that:
    + One element / number is returned.
    + One dimension is returned.
    + A subset of a dimension is returned.
3. What is the difference between `[x:]` and `[x, ...]`? (hint, try each on high-dimension arrays).
    
*Exactly what you choose to return is not imporant at this point, the goal of this task is to train you so that if you are given an n-dimension NumPy array, you can write an index or slice that returns a subset of desired positions.*

In [19]:
arr = np.random.random((3,3))
print("full array:")
print(arr, "\n")
print("first element:")
print(arr[0,0], "\n")
print("first dimension 1x3:")
print(arr[0, ], "\n")
print("subset of array first 2 rows:")
print(arr[0:2])
#[x:] is for subsets and [x, ...] is for elements 
# and specific dimensions individually 

full array:
[[0.40087655 0.01732334 0.14563461]
 [0.09085082 0.9582628  0.69560608]
 [0.16001913 0.3485672  0.15690243]] 

first element:
0.40087654639154313 

first dimension 1x3:
[0.40087655 0.01732334 0.14563461] 

subset of
[[0.40087655 0.01732334 0.14563461]
 [0.09085082 0.9582628  0.69560608]]


## Task 3a: Boolean Indexing

In the practice notebook perform the following:

+ Experiment with the following boolean conditionals to generate boolean arrays for indexing:
  + Greater than
  + Less than
  + Equals
  + Combine two or more of the above with:
      + or `|`
      + and `&`

You can create arrays or use existing ones

In [42]:
arr2 = np.random.random((3,5))
print("full array", arr2)
print("\n","greater than 0.5:")
print(arr2 > 0.5)
print("\n", "less than 0.3:")
print(arr2 < 0.3)
print("\n", "equals 0.4:")
print(arr2 == 0.4)
print("\n", "greater than 0.9 OR less than 0.1:")
print((arr2 > 0.9) | (arr2 < 0.1))
print("\n", "greater than 0.6 AND less than 0.9:")
print((arr2 > 0.6) & (arr2 < 0.9))

full array [[0.31527319 0.52630135 0.32294231 0.2834127  0.52205858]
 [0.1000314  0.96772039 0.65014124 0.68401226 0.75578651]
 [0.41777372 0.39674283 0.32426829 0.27589452 0.14809133]]

 greater than 0.5:
[[False  True False False  True]
 [False  True  True  True  True]
 [False False False False False]]

 less than 0.3:
[[False False False  True False]
 [ True False False False False]
 [False False False  True  True]]

 equals 0.4:
[[False False False False False]
 [False False False False False]
 [False False False False False]]

 greater than 0.9 OR less than 0.1:
[[False False False False False]
 [False  True False False False]
 [False False False False False]]

 greater than 0.6 AND less than 0.9:
[[False False False False False]
 [False False  True  True  True]
 [False False False False False]]


## Task 4a: Getting Help

In the practice notebook perform the following:

+ In the code cell below, call `help()` on two of the following functions: `np.transpose()`, `np.reshape()`, `np.resize()`, `np.ravel()`, `np.append()`, `np.delete()`, `np.concatenate()`, `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.vsplit()`, `np.hsplit()` 
+ Respond to this question: Did you understand the help docuemntation? Could you use the function just by looking at what the help says about it?  

In [43]:
help(np.column_stack)
help(np.vsplit)
# while it explained paramaters and provided an example
# it is possible I may need to look more into a function
# before I fully decide to use it to ensure it is the 
# right fit for my code

Help on function column_stack in module numpy:

column_stack(tup)
    Stack 1-D arrays as columns into a 2-D array.
    
    Take a sequence of 1-D arrays and stack them as columns
    to make a single 2-D array. 2-D arrays are stacked as-is,
    just like with `hstack`.  1-D arrays are turned into 2-D columns
    first.
    
    Parameters
    ----------
    tup : sequence of 1-D or 2-D arrays.
        Arrays to stack. All of them must have the same first dimension.
    
    Returns
    -------
    stacked : 2-D array
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack, hstack, vstack, concatenate
    
    Examples
    --------
    >>> a = np.array((1,2,3))
    >>> b = np.array((2,3,4))
    >>> np.column_stack((a,b))
    array([[1, 2],
           [2, 3],
           [3, 4]])

Help on function vsplit in module numpy:

vsplit(ary, indices_or_sections)
    Split an array into multiple sub-arrays vertically (row-wise).
    
    Please refer to th

## Task 5a: Transposing an Array

In the practice notebook perform the following:

+ Create a matrix of any size and transpose it.

In [46]:
arr3 = np.random.random((3,4))
print("original array:\n", arr3)
print("\ntranposed array:\n", arr3.T)

original array:
 [[0.26933576 0.55536769 0.20003511 0.59842408]
 [0.7649421  0.48362057 0.59230662 0.74017813]
 [0.2674209  0.85837159 0.80367982 0.33305285]]

tranposed array:
 [[0.26933576 0.7649421  0.2674209 ]
 [0.55536769 0.48362057 0.85837159]
 [0.20003511 0.59230662 0.80367982]
 [0.59842408 0.74017813 0.33305285]]


## Task 5b: Reshaping an Array

In the practice notebook peform the following:

+ Create a matrix and resize it by adding 2 extra columns
+ Create a matrix and resize it by adding 1 extra row
+ Create a matrix of 8 x 2 and resize it to 4 x 4

In [52]:
arr4 = np.random.random((2,3))
print("original array:\n", arr4)
print("\n2 more columns:\n", np.resize(arr4,(2,5)))
arr5 = np.array([[0,1,2,3],[4,5,6,7]])
print("\noriginal array:\n", arr5)
print("\n1 more row:\n", np.resize(arr5,(3,4)))
arr6 = np.random.random((8,2))
print("\noriginal array:\n", arr6)
print("\nresize to a 4x4:\n", np.resize(arr6,(4,4)))

original array:
 [[0.76298288 0.26522552 0.67014817]
 [0.66042018 0.88970089 0.29001511]]

2 more columns:
 [[0.76298288 0.26522552 0.67014817 0.66042018 0.88970089]
 [0.29001511 0.76298288 0.26522552 0.67014817 0.66042018]]

original array:
 [[0 1 2 3]
 [4 5 6 7]]

1 more row:
 [[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]]

original array:
 [[0.91043925 0.75027087]
 [0.88237516 0.45157728]
 [0.49243228 0.44254314]
 [0.15888891 0.58785596]
 [0.59856013 0.22983598]
 [0.46653996 0.17954722]
 [0.66872465 0.16308022]
 [0.6249572  0.50398778]]

resize to a 4x4:
 [[0.91043925 0.75027087 0.88237516 0.45157728]
 [0.49243228 0.44254314 0.15888891 0.58785596]
 [0.59856013 0.22983598 0.46653996 0.17954722]
 [0.66872465 0.16308022 0.6249572  0.50398778]]


## Task 5c: Appending to an Array

In the practice notebook perform the following:

 + Create a three dimensional array and append another row to the array
 + Append another colum to the array
 + Print the final results

In [67]:
arr7 = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("original:\n", arr7)
print("\nnew row:\n", np.append(arr7, [[4,4,4]], axis = 0))
print("\nnew column:\n", np.append(arr7, [[1],[2],[3]], axis = 1))

original:
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

new row:
 [[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]

new column:
 [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


## Task 5d: Inserting and Deleting Elements

In the practice notebook perform the following:

+ Examine the `help()` documentation for how to use the `insert()` and `delete()` functions.
+ Create a matrix and practice inserting a row and deleting a column.

In [75]:
help(np.insert)
help(np.delete)
arr8 = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("inserted row:\n", np.insert(arr8, 0, [[4,4,4]], axis = 0))
print("\ndeleted column:\n", np.delete(arr8, 1, 0))

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

## Task 5e: Joining Arrays

In the practice notebook perform the following:

+ Execute the code (in the cell below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [76]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
# the to arrays are simply being put together, as said sim to append
print(np.concatenate((my_array, x)))

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
# when inserting an array stacks it vertically
print(np.vstack((my_array, my_2d_array)))

# Stack arrays horizontally
print("\nhstack:")
#when inserting array stacks them horizontally next to each other
print(np.hstack((my_2d_array, my_2d_array)))

# Stack arrays column-wise
print("\ncolumn_stack:")
#cannot tell difference here between column_stack and hstack
print(np.column_stack((my_2d_array, my_2d_array)))

concatenate:
[1 2 3 4 1 1 1 1]

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


## Task 5d: Splitting Arrays

In the practice notebook perform the following:

+ Execute the code (as shown below).
+ Examine the output from each of the function calls in the cell above. If needed to understand, review the help pages for each tool either using the `help()` command or the [Numpy Function Reference](https://docs.scipy.org/doc/numpy/reference/routines.html). 
+ Respond to the following question and respond in the second cell below.
  + Can you identify what is happening with each of them?

In [77]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
#split the arrray at the 2nd index so that it was 2x2 and 2x2 top and bottom still
print(np.hsplit(my_2d_array, 2))

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
#splits the array into 2 sections row wise 
print(np.vsplit(my_2d_array, 2))

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
