In [1]:
#import numpy\n
import numpy as np

###Task 1a: Setup\n,
\n,
In the practice notebook, import the following packages:\n,
+ `numpy` as `np`

##2. The NumPy Array\n,
Using built-in Python lists, arrays are created in the following way:\n,
\n,
```python\n,
# A 1-dimensional list of numbers.\n,
my_array = [1,2,3] \n,
\n
# A 2-dimensional list of numbers.\n,
my_2d_array = [[1,2,3],[4,5,6]]\n,
\n
# A 3-dimensional list of numbers. \n,
my_3d_array = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]\n,
\n
# Two lists of boolean values\n,
a = [True, True, False, False]\n,
b = [False, False, True, True]\n,
\n

```python\n,
# A 1-dimensional list of numbers.\n,
my_array = np.array([1,2,3])\n,
\n,
# A 2-dimensional list of numbers.\n,
my_2d_array = np.array([[1,2,3],[4,5,6]])\n,
\n,
# A 3-dimensional list of numbers. \n,
my_3d_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])\n,
\n
# Two lists of boolean values\n,
a = np.array([True, True, False, False])\n,
b = np.array([False, False, True, True])\n,
```\n,
\n

## Task 2a: Creating Arrays\n,
\n,
one_array = np.array([1,1,1])\n,
two_array = np.array([[1,1,1],[2,2,2]])\n,
three_array = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]]\n,

In [38]:
# 2a
one_array = np.array([1,1,1])
two_array = np.array([[1,1,1],[2,2,2]])
three_array = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print(one_array)
print(two_array)
print(three_array)

[1 1 1]
[[1 1 1]
 [2 2 2]]
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]


In [39]:
# 3a
my_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
#prints array
print(my_array)
#prints number of dimensions for the array
print(my_array.ndim)
#prints tuple of array dimensions
print(my_array.shape)
#prints data type
print(my_array.dtype)
#prints the method of array
print(my_array.item)
#prints number of elements in array
print(my_array.size)
#prints buffer object pointing to strat of array's data
print(my_array.data)
#prints total bytes consumed by the elements of the array
print(my_array.nbytes)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3
(2, 2, 3)
int64
<built-in method item of numpy.ndarray object at 0x11d8b3c60>
12
96


In [70]:
# 4a
# prints an array of ones
ones = np.ones((2,3))
print(ones)
# prints and array of zeros
zeros = np.zeros((1,2))
print(zeros)
#returns new array of given shape and type without initializing entries
empty = np.empty((3,4))
print(empty)
#returns new array of given shape and type without initializing entries
fulls = np.full((2,2), 3)
print(fulls)
#return evenly spaced values within given interval
ara = np.arange(3)
print(ara)
#print evenly spaced numbers over an interval
space = np.linspace(4.0, 8.0, num=5)
print(space)
#returns random floats in interval [0.0, 1.0]
rando = np.random.random_sample()
print(rando)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]]
[[6.e-323 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000]]
[[3 3]
 [3 3]]
[0 1 2]
[4. 5. 6. 7. 8.]
0.7153060281844948


In [67]:
# 5.1
demo_a = np.ones((3,4))
demo_b = np.random.random((3,4))
print(demo_a)
print(demo_b)
demo_a + demo_b 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.40983627 0.34242919 0.46596863 0.85778943]
 [0.93397182 0.68235654 0.67169396 0.07720732]
 [0.97699087 0.88952318 0.46448938 0.48974968]]


array([[1.40983627, 1.34242919, 1.46596863, 1.85778943],
       [1.93397182, 1.68235654, 1.67169396, 1.07720732],
       [1.97699087, 1.88952318, 1.46448938, 1.48974968]])

In [71]:
## 5.2
#create the arrays
demo_c = np.ones((3,4))
demo_d = np.arange(4)
print(demo_c)
print(demo_d)
demo_c + demo_d

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [73]:
## 5.3
demo_e = np.ones((3,4))
demo_f = np.random.random((5, 1, 4))
print(demo_e)
print(demo_f)
result = demo_e + demo_f
print(result)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0.53124239 0.11849018 0.18916708 0.04601341]]

 [[0.49790991 0.82229719 0.02791056 0.92986125]]

 [[0.1253962  0.05305783 0.41106595 0.55256445]]

 [[0.83529386 0.33027253 0.18937384 0.23824314]]

 [[0.07588098 0.64888041 0.60704429 0.71789515]]]
[[[1.53124239 1.11849018 1.18916708 1.04601341]
  [1.53124239 1.11849018 1.18916708 1.04601341]
  [1.53124239 1.11849018 1.18916708 1.04601341]]

 [[1.49790991 1.82229719 1.02791056 1.92986125]
  [1.49790991 1.82229719 1.02791056 1.92986125]
  [1.49790991 1.82229719 1.02791056 1.92986125]]

 [[1.1253962  1.05305783 1.41106595 1.55256445]
  [1.1253962  1.05305783 1.41106595 1.55256445]
  [1.1253962  1.05305783 1.41106595 1.55256445]]

 [[1.83529386 1.33027253 1.18937384 1.23824314]
  [1.83529386 1.33027253 1.18937384 1.23824314]
  [1.83529386 1.33027253 1.18937384 1.23824314]]

 [[1.07588098 1.64888041 1.60704429 1.71789515]
  [1.07588098 1.64888041 1.60704429 1.71789515]
  [1.07588098 1.64888041

In [88]:
###5a

raya = np.ones((2,3))
rayb = np.random.random((4, 1, 3))
print(raya)
print(rayb)
added = raya + rayb
print(added)
subbeda = raya - rayb
print(subbeda)
subbedb = rayb - raya
print(subbedb)
mult = raya * rayb
print(mult)

[[1. 1. 1.]
 [1. 1. 1.]]
[[[0.31080175 0.935504   0.33917383]]

 [[0.95335489 0.72533556 0.91644024]]

 [[0.72685589 0.11930646 0.46544427]]

 [[0.9896889  0.72819201 0.68100857]]]
[[[1.31080175 1.935504   1.33917383]
  [1.31080175 1.935504   1.33917383]]

 [[1.95335489 1.72533556 1.91644024]
  [1.95335489 1.72533556 1.91644024]]

 [[1.72685589 1.11930646 1.46544427]
  [1.72685589 1.11930646 1.46544427]]

 [[1.9896889  1.72819201 1.68100857]
  [1.9896889  1.72819201 1.68100857]]]
[[[0.68919825 0.064496   0.66082617]
  [0.68919825 0.064496   0.66082617]]

 [[0.04664511 0.27466444 0.08355976]
  [0.04664511 0.27466444 0.08355976]]

 [[0.27314411 0.88069354 0.53455573]
  [0.27314411 0.88069354 0.53455573]]

 [[0.0103111  0.27180799 0.31899143]
  [0.0103111  0.27180799 0.31899143]]]
[[[-0.68919825 -0.064496   -0.66082617]
  [-0.68919825 -0.064496   -0.66082617]]

 [[-0.04664511 -0.27466444 -0.08355976]
  [-0.04664511 -0.27466444 -0.08355976]]

 [[-0.27314411 -0.88069354 -0.53455573]
  [-0.2

In [4]:
###6a
ray1 = np.ones((2,5))
print(ray1)
# sum of array elements
sumray1 = np.sum(ray1)
print(sumray1)
ray2 = np.random.random((4,3))
print(ray2)
#minimum element wise of array
minray2 = np.minimum(ray2)
print(minray2)
#maximum element wise of array
maxray2 = np.max(ray2)
print(maxray2)
ray3 = np.array([[3,4],[2,2]])
print(ray3)
# returns cumulative sum of elements
cumray3 = np.cumsum(ray3)
print(cumray3)
#returns mean from elements
meanray3 = np.mean(ray3)
print(meanray3)
ray4 = np.arange(3,6)
print(ray4)
# returns product moment correlation coefficients
np.corrcoef(ray4)
ray5 = np.array([[[1,7],[2,4]],[[3,6],[4,2]]])
print(ray5)
# returns standard deviation of elements
stdray5 = np.std(ray5)
print(stdray5)
# returns variance of elements
varray5 = np.var(ray5)
print(varray5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
10.0
[[0.13487592 0.22357879 0.50104841]
 [0.59291716 0.74268276 0.79859496]
 [0.47275829 0.05617881 0.22194187]
 [0.7801652  0.12347553 0.34613713]]


ValueError: invalid number of arguments

In [103]:
#6.1
a = [True, True, False, False]
b = [False, False, True, True]
boom = np.logical_or(a, b)
print(boom)
yeah = np.logical_and(a, b)
print(yeah)

[ True  True  True  True]
[False False False False]


In [105]:
#6b
one = [True, True, True, False]
two = [False, False, True, False]
ch_or = np.logical_or(one, two)
#compute truth values of x1 OR x2 element wise
print(ch_or)
#compute truth values of x1 AND x2 element wise
ch_and = np.logical_and(one, two)
print(ch_and)
#compute truth values of NOT element wise
ch_not = np.logical_not(one)
print(ch_not)

[ True  True  True False]
[False False  True False]
[False False False  True]
